plugins:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2.3
  EnabledByDefault: true

#################### Bundler ##############################

Bundler/GemComment:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

#################### Layout ###############################

Layout/AccessModifierIndentation:
  EnforcedStyle: indent
  IndentationWidth: ~

Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  SupportedHashRocketStyles:
    - key
    - separator
    - table
  EnforcedColonStyle: key
  SupportedColonStyles:
    - key
    - separator
    - table
  EnforcedLastArgumentHashStyle: always_inspect
  SupportedLastArgumentHashStyles:
    - always_inspect
    - always_ignore
    - ignore_implicit
    - ignore_explicit

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation
  IndentationWidth: ~

Layout/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: false
  IndentationWidth: ~

Layout/DotPosition:
  EnforcedStyle: leading
  SupportedStyles:
    - leading
    - trailing

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: false
  NumberOfEmptyLines: 1

Layout/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines
  SupportedStyles:
    - empty_lines
    - no_empty_lines

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines
  SupportedStyles:
    - empty_lines
    - empty_lines_except_namespace
    - empty_lines_special
    - no_empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines
  SupportedStyles:
    - empty_lines
    - empty_lines_except_namespace
    - empty_lines_special
    - no_empty_lines

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ExtraSpacing:
  AllowForAlignment: true
  ForceEqualSignAlignment: false

Layout/FirstArgumentIndentation:
  EnforcedStyle: special_for_inner_method_call_in_parentheses
  SupportedStyles:
    - consistent
    - special_for_inner_method_call
    - special_for_inner_method_call_in_parentheses
  IndentationWidth: ~

Layout/IndentationConsistency:
  EnforcedStyle: normal
  SupportedStyles:
    - normal

Layout/SingleLineBlockChain:
  Enabled: false

Layout/IndentationWidth:
  Width: 2

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
  SupportedStyles:
    - special_inside_parentheses
    - consistent
    - align_brackets
  IndentationWidth: ~

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
  SupportedStyles:
    - special_inside_parentheses
    - consistent
    - align_braces
  IndentationWidth: ~

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: symmetrical
  SupportedStyles:
    - symmetrical
    - new_line
    - same_line

Layout/MultilineAssignmentLayout:
  SupportedTypes:
    - block
    - case
    - class
    - if
    - kwbegin
    - module
  EnforcedStyle: same_line
  SupportedStyles:
    - same_line
    - new_line

Layout/MultilineHashBraceLayout:
  EnforcedStyle: symmetrical
  SupportedStyles:
    - symmetrical
    - new_line
    - same_line

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: symmetrical
  SupportedStyles:
    - symmetrical
    - new_line
    - same_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  SupportedStyles:
    - aligned
    - indented
    - indented_relative_to_receiver
  IndentationWidth: ~

Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: symmetrical
  SupportedStyles:
    - symmetrical
    - new_line
    - same_line

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned
  SupportedStyles:
    - aligned
    - indented
  IndentationWidth: ~

Layout/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: no_space
  SupportedStylesInsidePipes:
    - space
    - no_space

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space
  SupportedStyles:
    - space
    - no_space

Layout/SpaceAroundOperators:
  AllowForAlignment: true

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space
  SupportedStyles:
    - space
    - no_space

Layout/SpaceBeforeFirstArg:
  AllowForAlignment: true

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_no_space
  SupportedStyles:
    - require_no_space
    - require_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  SupportedStyles:
    - space
    - no_space
  EnforcedStyleForEmptyBraces: space
  SupportedStylesForEmptyBraces:
    - space
    - no_space
  SpaceBeforeBlockParameters: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  SupportedStyles:
    - space
    - no_space
    - compact
  EnforcedStyleForEmptyBraces: no_space
  SupportedStylesForEmptyBraces:
    - space
    - no_space

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space
  SupportedStyles:
    - space
    - no_space

Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline
  SupportedStyles:
    - final_newline
    - final_blank_line

Layout/BlockAlignment:
  EnforcedStyleAlignWith: either

Layout/DefEndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  SupportedStylesAlignWith:
    - keyword
    - variable
    - start_of_line

#################### Lint ##################################

Lint/Debugger:
  Include:
    - app/**/*.rb

Lint/ConstantResolution:
  Enabled: false

Lint/InheritException:
  EnforcedStyle: runtime_error
  SupportedStyles:
    - runtime_error
    - standard_error

Lint/NumberConversion:
  Enabled: false

Lint/SafeNavigationChain:
  AllowedMethods:
    - present?
    - blank?
    - presence

Lint/UnusedBlockArgument:
  IgnoreEmptyBlocks: true
  AllowUnusedKeywordArguments: false

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: false
  IgnoreEmptyMethods: true

#################### Performance ###########################
Performance/ChainArrayAllocation:
  Enabled: false

Performance/DoubleStartEndWith:
  IncludeActiveSupportAliases: true

Performance/RedundantMerge:
  MaxKeyValuePairs: 2

#################### Metrics ###############################
Metrics/AbcSize:
  Max: 37

Metrics/BlockLength:
  Max: 200

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 20

Layout/LineLength:
  Max: 160

Metrics/ModuleLength:
  Max: 150

Metrics/MethodLength:
  CountComments: false
  Max: 50

Metrics/ParameterLists:
  Max: 6
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 20

#################### Naming ################################

Naming/PredicatePrefix:
  NamePrefix:
    - is_
    - has_
    - have_
  ForbiddenPrefixes:
    - is_
    - has_
    - have_
  AllowedMethods:
    - is_a

Naming/VariableName:
  EnforcedStyle: snake_case
  SupportedStyles:
    - snake_case
    - camelCase

Naming/VariableNumber:
  EnforcedStyle: snake_case

#################### Styles ################################

Style/Alias:
  EnforcedStyle: prefer_alias
  SupportedStyles:
    - prefer_alias
    - prefer_alias_method

Style/BarePercentLiterals:
  EnforcedStyle: bare_percent
  SupportedStyles:
    - percent_q
    - bare_percent

Style/BlockDelimiters:
  EnforcedStyle: line_count_based
  SupportedStyles:
    - line_count_based
    - semantic
    - braces_for_chaining
  ProceduralMethods:
    - benchmark
    - bm
    - bmbm
    - create
    - each_with_object
    - measure
    - new
    - realtime
    - tap
    - with_object
  FunctionalMethods:
    - let
    - let!
    - subject
    - watch

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/ConditionalAssignment:
  EnforcedStyle: assign_to_condition
  SupportedStyles:
    - assign_to_condition
    - assign_inside_condition
  SingleLineConditionsOnly: true
  IncludeTernaryExpressions: true

Style/ConstantVisibility:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/For:
  EnforcedStyle: each
  SupportedStyles:
    - for
    - each

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  SupportedStyles:
    - when_needed
    - always
    - never

Style/GlobalVars:
  AllowedVariables: []

Style/HashSyntax:
  EnforcedStyle: ruby19
  SupportedStyles:
    - ruby19
    - hash_rockets
    - no_mixed_keys
    - ruby19_no_mixed_keys
  UseHashRocketsWithSymbolValues: false
  PreferHashRocketsForNonAlnumEndingSymbols: false

Style/ImplicitRuntimeError:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal
  SupportedStyles:
    - line_count_dependent
    - lambda
    - literal

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/NonNilCheck:
  IncludeSemanticChanges: false

Style/NumericLiterals:
  MinDigits: 5
  Strict: false

Style/ParenthesesAroundCondition:
  AllowSafeAssignment: true

Style/RedundantReturn:
  AllowMultipleReturnValues: false

Style/Semicolon:
  AllowAsExpressionSeparator: false

Style/Send:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  ConsistentQuotesInMultiline: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/SymbolArray:
  EnforcedStyle: percent
  SupportedStyles:
    - percent
    - brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma

Style/TrivialAccessors:
  ExactNameMatch: true
  AllowPredicates: true

  AllowDSLWriters: false
  IgnoreClassMethods: false
  AllowedMethods:
    - to_ary
    - to_a
    - to_c
    - to_enum
    - to_h
    - to_hash
    - to_i
    - to_int
    - to_io
    - to_open
    - to_path
    - to_proc
    - to_r
    - to_regexp
    - to_str
    - to_s
    - to_sym

Style/WordArray:
  EnforcedStyle: percent
  SupportedStyles:
    - percent
    - brackets
  MinSize: 0
  WordRegex: !ruby/regexp '/\A[\p{Word}\n\t]+\z/'
