# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Read Ruby version
      id: ruby-version
      run: echo "version=$(cat .ruby-version | tr -d 'ruby-')" >> $GITHUB_OUTPUT
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ steps.ruby-version.outputs.version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Setup Firefox
      uses: browser-actions/setup-firefox@v1
    - name: Setup geckodriver
      uses: browser-actions/setup-geckodriver@latest
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run RuboCop
      run: bundle exec rubocop
    - name: Run tests
      env:
        GOODREADS_SECRET: ${{ secrets.GOODREADS_SECRET }}
        GOODREADS_API_KEY: ${{ secrets.GOODREADS_API_KEY }}
        GOODREADS_EMAIL: ${{ secrets.GOODREADS_EMAIL }}
        GOODREADS_PASSWORD: ${{ secrets.GOODREADS_PASSWORD }}
        GOODREADS_USER_ID: ${{ secrets.GOODREADS_USER_ID }}
        GOODREADS_ACCESS_TOKEN: ${{ secrets.GOODREADS_ACCESS_TOKEN }}
        GOODREADS_ACCESS_TOKEN_SECRET: ${{ secrets.GOODREADS_ACCESS_TOKEN_SECRET }}
        OVERDRIVE_KEY: ${{ secrets.OVERDRIVE_KEY }}
        OVERDRIVE_SECRET: ${{ secrets.OVERDRIVE_SECRET }}
        BOOKMOOCH_USERNAME: ${{ secrets.BOOKMOOCH_USERNAME }}
        BOOKMOOCH_PASSWORD: ${{ secrets.BOOKMOOCH_PASSWORD }}
        RACK_ENV: test
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      run: bundle exec rake
