# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: yonderbook_test
        ports:
          - 5432/tcp

    strategy:
      matrix:
        ruby-version: ['3.2.3']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      env:
        GOODREADS_SECRET: ${{ secrets.GOODREADS_SECRET }}
        GOODREADS_API_KEY: ${{ secrets.GOODREADS_API_KEY }}
        OVERDRIVE_KEY: ${{ secrets.OVERDRIVE_KEY }}
        OVERDRIVE_SECRET: ${{ secrets.OVERDRIVE_SECRET }}
        GOODREADS_EMAIL: ${{ secrets.GOODREADS_EMAIL }}
        GOODREADS_PASSWORD: ${{ secrets.GOODREADS_PASSWORD }}
        BOOKMOOCH_USERNAME: ${{ secrets.BOOKMOOCH_USERNAME }}
        BOOKMOOCH_PASSWORD: ${{ secrets.BOOKMOOCH_PASSWORD }}
        RACK_ENV: ${{ secrets.RACK_ENV }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      run: bundle exec rake
